spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1ks66d7iou183cnqo.mysql.rds.aliyuncs.com:3306/dbgirl?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Wang1993
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


